---
title: "DataReduction"
author: "JDW"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Reduction

### Load libraries
```{r libs, echo=TRUE, results='asis', message=FALSE, warning=FALSE}
#strftime(),base: https://stat.ethz.ch/R-manual/R-devel/library/base/html/strptime.html
#lubridate package: https://www.rdocumentation.org/packages/lubridate/versions/1.9.2

library(tidyverse)
library(knitr)
setwd("~/GitHub/DSCI605/Mod10")
```

### Get the data
```{r readData, echo=TRUE}
######Three-year crime data from 2017-09-01 to 2020-08-31
crime_bat <- readRDS("Crime3years.rds")
## Select two-years
two_years_data <- crime_bat %>%
  filter(Date >= "2018-01-01" & Date <= "2019-12-31")
```

### Hourly crime
```{r plotHourly}
#Basic time series based on scatter plot
two_years_data %>% ggplot(aes(x = Date, y = Battery)) +
  geom_point(col = "maroon") + 
  geom_line(col = "red") +
  labs(title = "Battery Crime from 2018-01-01 to 2019-12-31 in Chicago", 
       x = "Hourly", y = "Number of Crimes")
```

## Create new variables
```{r newvar, echo=TRUE}
##Create new variables
bat_train_new<-two_years_data %>% 
  mutate(month = month(two_years_data$Date),year=year(two_years_data$Date))
```

### Group data by month
```{r grpdata, echo=TRUE}
#How to group the data into Monthly (every 30/31 days) data
bat_train_monthly <- bat_train_new %>% 
  group_by(month,year) %>%
  summarize(case_monthly=sum(Battery)) %>%
  mutate(yearmonth=sprintf("%04d%02d", year, month))
```

### First Monthly Plot
```{r plotmnth, echo=TRUE}
#####First try for graphing
bat_train_monthly%>% 
  ggplot(aes(x = yearmonth, y = case_monthly,group=1)) +
  geom_point(col = "maroon") + geom_line(col = "red") +
  labs(title = "Battery Crime from 2018-01-01 to 2019-12-31 in Chicago", 
       x = "Month", y = "Number of Crimes") 
```

### Sort my dates
```{r sortDates, wcho=TRUE}
bat_train_monthly_sorted <- bat_train_monthly %>%
  arrange(yearmonth)
```

### Clearer plot
```{r plotClear, echo=TRUE}
#########The best result
# Convert the yearmonth to a proper Date format
bat_train_monthly_sorted <- bat_train_monthly_sorted %>%
  mutate(yearmonth = as.Date(paste0(substr(yearmonth, 1, 4), "-", 
                                      substr(yearmonth, 5, 6), "-01")))
bat_train_monthly_sorted %>%
  ggplot(aes(x = yearmonth, y = case_monthly,group=1)) +
  geom_point(col = "maroon") + geom_line(col = "red") +
  labs(title = "Battery Crime from 2018-01-01 to 2019-12-31 in Chicago",
       x = "Year-Month", y = "Number of Crimes")+
  scale_x_date(date_breaks = "3 months", date_labels = "%Y-%m")
```

### Insert table
Create the first table:
```{r tab1,include=TRUE, echo=FALSE, results='asis'}
top_cr <- bat_train_monthly_sorted %>%
  select(-yearmonth)
#save the data frame
saveRDS(top_cr, file="Crime2years_monthly.rds")

knitr::kable(top_cr,caption= "Battery Crime at a month scale from 2018-01-01 to 2019-12-31",digits=4)

```
In Table 1, we see the the sorted months and their battery crime rate for 2 years.
